server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-containers
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: pipeline-sonar-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: sonar-commit-logs
          __path__: /var/pipeline-data/sonar-work/*/*/logs/*.log

  - job_name: pipeline-dead-letter
    static_configs:
      - targets: [localhost]
        labels:
          job: dead-letter
          __path__: /var/pipeline-data/dead_letter/*.json

  - job_name: pipeline-error-files
    static_configs:
      - targets: [localhost]
        labels:
          job: pipeline-error-files
          __path__: /var/pipeline-data/error_logs/*.log
